[config]
schemaVersion = "0.1.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "dantayy"
name = "PEAKReactBot"
description = "Make BingBong use ReactBot voicelines to replace their default voicelines with a much wider variety!"
websiteUrl = "https://github.com/dantayy/PEAKReactBot"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_PEAK = "5.4.2403"
loaforc-loaforcsSoundAPI = "2.0.8"

[build]
icon = "../../icon.png"
readme = "../../README.md"
outdir = "../../artifacts/thunderstore/"

[[build.copy]]
source = "../../artifacts/bin/PEAKReactBot/release/com.github.com.dantayy.PEAKReactBot.dll"
target = "plugins/"

[[build.copy]]
source = "../../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../../LICENSE"
target = "/"

[[build.copy]]
source = "../../replacers"
target = "plugins/replacers"

[[build.copy]]
source = "../../sounds"
target = "plugins/sounds"

[[build.copy]]
source = "../../sound_pack.json"
target = "plugins/"

# The following config options only apply when using TCLI to publish to Thunderstore directly:

[publish]
# See communities at:
# https://thunderstore.io/api/experimental/community/
communities = [ "peak", ]

[publish.categories]
# See categories at:
# https://thunderstore.io/api/experimental/community/peak/category/
peak = [ "mods", ]
